
# LSOracle for partitioning
lsoracle: '/home/jingxiao/Tools/LSOracle/build/core/lsoracle'

# Synthesis
yosys: 'yosys'

# Simulation
iverilog: 'iverilog'
vvp: 'vvp'

# ABC for synthesis
abc: '/home/jingxiao/Tools/abc/abc'

# OpenSTA for delay and power analysis
OpenSTA: '/home/jingxiao/Tools/OpenSTA/app/sta'
